version: "3.9"
services:
  insights-backend:
    container_name: insights-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - /root/insights/.env:/home/appuser/app/.env
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /root/insights/logs/nginx/logs:/app/logs/
      - /root/insights/certificates/letsencrypt:/etc/letsencrypt/
      - /root/insights/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - insights-backend
    restart: always